### ISSUE TITLE
Problems with Linux Packages

### ISSUE THREAD

**Issue by boehmseb** [ocraft/ocraft-s2client#10] opened 2019-04-16 10:03 UTC
I have recently encountered some issues with how ocraft tries to launch starcraft when using the [Linux packages](url).

- there is no support directory needed and the packages do not contain a directory called `Support64`. While this can be easily fixed by creating an empty directory of that name, it would be nice to be able to specify the support directory or to say that none should be used
- the way how the most recent executable version is determined does not work properly as there are also directories of the form `ShadersXXXXX` which always are detected as "newer" than any of the `BaseXXXXX` directories containing the actual starcraft executables. A quick fix at my side is deleting such directories but I do not know for what they are used and whether they are needed for rendering. A better solution that comes to my mind would be filtering the directories in the versions directory for those which contain a file with the name of the executable. 

If I should assist by creating a pull request, just say so. Otherwise, keep up the good work :)

**Comment by ocraft** [comment] 2019-04-16 10:30
Duplicate of #9 

It's the same class of problem like in this issue https://github.com/ocraft/ocraft-s2client/issues/9

**Closed by ocraft** 2019-04-16 10:30 UTC
Labels: duplicate
